version: '3'
services:
  postgres:
    image: 'postgres:11'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.postgres:/var/lib/postgresql/data
  django:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - '.:/opt/btk'
      - '/tmp/btk:/tmp/btk'
    ports:
      - '8000:8000'
    depends_on:
      - postgres
  ci:
    build: .
    volumes:
      - '.:/opt/btk'
    command: bash -c "isort -rc . && black . && flake8 ."
