# Generated by Django 3.0.5 on 2020-04-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="name",
            field=models.CharField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
