# Generated by Django 3.0.5 on 2020-04-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="tags",
            field=models.ManyToManyField(to="tags.Tag"),
        ),
    ]
